### ISSUE TITLE
Help!~

### ISSUE THREAD

**Issue by 1633146782** [Cassie07/Review_Molecular_profile_prediction_GNN#1]
Hello, I ran into difficulties when running Data preprocessing. Could you please provide me with the data in terms of omics? Thank you

**Comment by Cassie07** [comment]
> Hello, I ran into difficulties when running Data preprocessing. Could you please provide me with the data in terms of omics? Thank you

Hello! You can download the omics-relevant data from cBioPortal (https://www.cbioportal.org/datasets) and generate your own molecular profile alteration labels. For example, if the patient has a KRAS mutation record, you can assign the label as 1; otherwise, you can assign it as 0.
